# Specifica l'architettura di base e dove trovare il Dockerfile
build_from:
  amd64: "hassioaddons/base-ubuntu:latest"
  armhf: "hassioaddons/base-ubuntu:latest"
  aarch64: "hassioaddons/base-ubuntu:latest"

# Indica che l'ambiente di build è nella sottocartella 'root'
dockerfile: root/Dockerfile
